osx_image: xcode8.2
language: objective-c
xcode_project: Diff.xcodeproj
xcode_scheme: Diff-Mac
before_install:
    - gem install xcpretty
git:
   depth: 3

script:
    - open -b com.apple.iphonesimulator
    - xcodebuild test -scheme DiffTests -project Diff.xcodeproj | xcpretty
